### ISSUE TITLE
Okay to reference this in the Logentries docs?

### ISSUE THREAD

**Issue by StephenHynes7** [ricbra/ansible-logentries#1]
Hey Richard,

Cheers for putting this together :) Would you mind if we reference to this page on our documentation? We haven't done anything for Ansible and I think it would be pretty cool to write up some instructions and reference you!

**Comment by ricbra** [comment]
Hi @StephenHynes7 ,

Sure, no problem. If you need any help let me know!

**Comment by ricbra** [comment]
Closing this one as a blog post is coming :)
