### ISSUE TITLE
Installs fails on Debian 9 stretch

### ISSUE THREAD

**Issue by tristanbes** [ricbra/ansible-logentries#21]
`E:The repository 'http://rep.logentries.com stretch Release' does not have a Release file`

**Comment by ricbra** [comment]
According to their documentation there is not support for stretch yet I guess: https://docs.logentries.com/v1.0/docs/linux-agent/

There is no entry for stretch or Debian 9.0.

**Comment by tristanbes** [comment]
Yes I saw that, but the fact that your playbook is failing on Debian 9 should be fixed.
You should fallback to latest distribution version (jessie) when running on debian 9.

What do you think ?

(Installing logentries from the jessie repository on stretch works)

**Comment by ricbra** [comment]
That would be a nice improvement indeed. Would you be interested in fixing this?

**Comment by tristanbes** [comment]
Will see what I can do, but not sure it's going to be a clean solution.

**Comment by ricbra** [comment]
Cool! Most simple solution would be a note in the README.md for now. Guess Logentries will add support soon enough.
